apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9113'
        fluentbit.io/parser: nginx
    spec:
      #nodeSelector:
        #stage: "yes"
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              memory: 15Mi
              cpu: "2m"
            limits:
              memory: 30Mi
              #cpu: "0.0003"
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
            #- name: nginx-logs-fsx
            #  mountPath: /var/log/nginx/
            #  subPath: nginx/
        #- name: nginx-exporter
        #  image: 'nginx/nginx-prometheus-exporter:latest'
        #  args:
        #    - '-nginx.scrape-uri=http://localhost/metrics'
        #  resizePolicy:
        #    - resourceName: memory
        #      restartPolicy: "RestartContainer"
        #    - resourceName: cpu
        #      restartPolicy: NotRequired
        #  resources:
        #    requests:
        #      memory: 15Mi
        #      cpu: "0.0001"
        #    limits:
        #      memory: 30Mi
        #      cpu: "0.0003"
        #  ports:
        #    - containerPort: 9113
        #      name: metrics
      volumes:
        - configMap:
            defaultMode: 420
            name: nginx-config
          name: nginx-config
        #- name: nginx-logs-fsx
        #  persistentVolumeClaim:
        #    claimName: pvc-smb-nginx
