apiVersion: v1
kind: Service
metadata:
  name: "nginx"
  namespace: "nginx"
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      name: http
      targetPort: 80
      protocol: TCP

    - port: 9113
      name: metrics
  type: NodePort
  selector:
    app: "nginx"
