apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx
data:
  nginx.conf: |
        log_format upstream_time '$remote_addr - $remote_user [$time_local] '
                             '"$request" $status $body_bytes_sent '
                             '"$http_referer" "$http_user_agent"'
                             'rt=$request_time uct="$upstream_connect_time" uht="$upstream_header_time" urt="$upstream_response_time"';
        server {
          listen 80;
          location / {
          root /usr/share/nginx/html;
          index index.html index.htm;
          }
          location /metrics {
          stub_status on;
          access_log /var/log/nginx/metrics.log upstream_time;
          #access_log on;
          }
        }
